import Loading from "@/components/Loading";
import Subject from "@/components/Subject";
import { subjectType } from "@/types/subject";
import Head from "next/head";
import React, { Key, useEffect, useState } from "react";

export default function status() {
	const [subjects, setSubjects] = useState<subjectType[]>([]);
	const [loading, setLoading] = useState(true);

	useEffect(() => {
		fetch("/api/status")
			.then((res) => res.json())
			.then((res) => {
				setSubjects(res.data);
				setLoading(false);
			});
	}, []);

	return (
		<>
			<Head>
				<title>Assignment Tracker</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{loading ? <Loading /> : <div className="appHolder">
            <div className="subjectHolder unclickable">
				{subjects
					.sort((first, second) => {
						return first.subject.localeCompare(second.subject);
					})
					.map((eachSub: subjectType) => (
						<Subject
							key={eachSub.subject as Key}
							data={eachSub}
						/>
					))}
			</div>
            </div>}
		</>
	);
}
